apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-cortex
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-cortex
spec:
  serviceName: {{ .Release.Name }}-cortex
  replicas: {{ .Values.cortex.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cortex
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cortex
    spec:
      terminationGracePeriodSeconds: {{ .Values.cortex.statefulset.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Release.Name }}-cortex
        image: {{ .Values.cortex.statefulset.containers.image }}
        ports:
          - containerPort: {{ .Values.cortex.statefulset.containers.ports.containerPort }}
            name: {{ .Values.cortex.statefulset.containers.ports.name }}
        resources:
          limits:
            cpu: {{ .Values.cortex.statefulset.containers.resources.limits.cpu }}
            memory: {{ .Values.cortex.statefulset.containers.resources.limits.memory }}
          requests:
            cpu: {{ .Values.cortex.statefulset.containers.resources.requests.cpu }}
            memory: {{ .Values.cortex.statefulset.containers.resources.requests.memory }}
        env:
          - name: es_uri
            value: http://{{ ternary (printf "%s-elasticsearch" .Release.Name) .Values.theHiveApp.statefulset.elasticSearchHostname .Values.elasticSearch.enabled }}:9200
          - name: kubernetes_job_pvc
            value: hppvc
        volumeMounts:
          - name: jobdir
            mountPath: /var/log/cortex
            subPath:  
      volumes:
        - name: jobdir
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-{{ .Values.CortexPersistentVolumeClaim.name }}"
