{{- if .Values.thehive.extraConfig  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thehive.fullname" . }}-config
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
data: |
  {{- toYaml .Values.thehive.extraConfig | nindent 2 }}
{{- end -}}
