{{- if .Values.extraConfig  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thehive.fullname" . }}-config
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
data:
  application.conf: |
    {{- toYaml .Values.extraConfig | nindent 4 }}
{{- end -}}
