################## HIVE CONFIGS
theHiveApp:
  service:
    type: LoadBalancer
    port: 9000
    nodePort: 30001
  statefulset:
    replicas: 1
    containerPort: 9000
    name: http
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: "100m"
        memory: 100Mi
    image: strangebee/thehive:latest
    cassandraHostname: "cassandra"
    elasticSearchHostname: "elasticSearch"
  volumes:
    items:
      key: application.conf
      path: application.conf


HiveStorageClass:
  cloud: hive-local
  name: hive-storageclass
  reclaimPolicy: Retain

HivePersistentVolumeClaim:
  name: hive-pvc
  spec:
    accessModes: ReadWriteOnce
    resources:
      requests:
        storage: 2Gi

HivePersistentVolume:
  name: hive-pv
  spec:
    accessModes: ReadWriteOnce
    capacity:
      storage: 5Gi
    hostPath:
      dirPath: /hive

ConfigMap:
  name: hive-svc

################## CASSANDRA CONFIG
cassandra:
  enabled: true
  service:
    port: 9042
  statefulset:
    replicas: 1
    terminationGracePeriodSeconds: 1800
    image: cassandra:4.0
    resources:
      limits:
        cpu: "500m"
        memory: 1Gi
      requests:
        cpu: "100m"
        memory: 100Mi

#################### ELASTICSEARCH
elasticSearch:
  enabled: true
  service:
    port: 9200
  statefulset:
    replicas: 1
    terminationGracePeriodSeconds: 1800
    initContainers:
      name: init
      image: debian:stable-slim
    containers:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
      ports:
        containerPort: 9200
        name: http
      resources:
        limits:
          cpu: "500m"
          memory: 1Gi
        requests:
          cpu: "100m"
          memory: 100Mi

####################### MINIO CONFIGS
minio:
  service:
    type: LoadBalancer
    apiName: api
    apiPort: 9017
    apitargetPort: 9000
    consoleName: console
    consolePort: 9018
    consoletargetPort: 9001
    consoleNodePort: 30018
  statefulset:
    replicas: 1
    terminationGracePeriodSeconds: 1800
    containers:
      image: quay.io/minio/minio
      ports:
        apiContainerPort: 9000
        apiName: api
        consoleContainerPort: 9001
        consoleName: console
      resources:
        limits:
          cpu: "500m"
          memory: 512Mi
        requests:
          cpu: "100m"
          memory: 100Mi

######################### CORTEX CONFIGS
cortex:
  service:
    port: 9543
    targetPort: 9001
  statefulset:
    replicas: 1
    terminationGracePeriodSeconds: 1800
    containers:
      image: thehiveproject/cortex:3.1.1-1
      ports:
        containerPort: 9001
        name: http
      resources:
        limits:
          cpu: "500m"
          memory: 1Gi
        requests:
          cpu: "100m"
          memory: 512Mi

CortexStorageClass:
  cloud: local
  name: cortex-storageclass
  reclaimPolicy: Retain
  accessModes: ReadWriteMany

CortexPersistentVolume:
  name: cortex-pv
  accessModes: ReadWriteMany
  capacity:
    storage: 5Gi

CortexPersistentVolumeClaim:
  name: cortex-pvc
  spec:
    resources:
      storage: 4G

CortexHPA:
  name: cortex-autoscale
  spec:
    minReplicas: 1
    maxReplicas: 2
    metrics:
      averageUtilization: 90
      averageValue: 900Mi


################ GLOBAL CONFIGS
# global:
  # cassandra:
  #   namespace: "cassandra"
  # elasticSearch:
  #   namespace: "elasticsearch"