theHiveApp:
  service:
    port: 9000
    nodePort: 30001
  deployments:
    replicas: 1
    containerPort: 9000
    name: http
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: "100m"
        memory: 100Mi
    image: strangebee/thehive:latest
    cassandraHostname: "cassandra"
    elasticSearchHostname: "elasticSearch"

cassandra:
  enabled: true
  service:
    port: 9042
  statefulset:
    replicas: 1
    terminationGracePeriodSeconds: 1800
    image: cassandra:4.0
    resources:
      limits:
        cpu: "500m"
        memory: 1Gi
      requests:
        cpu: "100m"
        memory: 100Mi

elasticSearch:
  enabled: true
  service:
    port: 9200
  statefulset:
    replicas: 1
    terminationGracePeriodSeconds: 1800
    initContainers:
      name: init
      image: debian:stable-slim
    containers:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
      ports:
        containerPort: 9200
        name: http
      resources:
        limits:
          cpu: "500m"
          memory: 1Gi
        requests:
          cpu: "100m"
          memory: 100Mi

minio:
  service:
    port: 9000
  statefulset:
    replicas: 1
    terminationGracePeriodSeconds: 1800
    containers:
      image: quay.io/minio/minio
      ports:
        containerPort: 9000
        name: http
      resources:
        limits:
          cpu: "500m"
          memory: 512Mi
        requests:
          cpu: "100m"
          memory: 100Mi


cortex:
  service:
    port: 9001
  statefulset:
    replicas: 1
    terminationGracePeriodSeconds: 1800
    containers:
      image: thehiveproject/cortex:3.1.1-1
      ports:
        containerPort: 9001
        name: http
      resources:
        limits:
          cpu: "500m"
          memory: 1Gi
        requests:
          cpu: "100m"
          memory: 512Mi
