{{- if or (.Values.cortex.configFile) (.Values.cortex.logbackXml) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortex.fullname" . }}-config
  {{- with .Values.cortex.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
data:
  {{- if .Values.cortex.configFile }}
  {{- $appConf := .Values.cortex.configFile }}
  {{- if .Values.cortex.k8sJobs.labels }}
    {{- $appConf = printf "%s\njob.kubernetes.labels {\n" $appConf }}
    {{- range $k, $v := .Values.cortex.k8sJobs.labels }}
      {{- $appConf = printf "%s  %q = %q\n" $appConf $k $v }}
    {{- end }}
    {{- $appConf = printf "%s}\n" $appConf }}
  {{- end }}
  application.conf: {{- $appConf | toYaml | indent 1 }}
  {{- end }}
  {{- if .Values.cortex.logbackXml }}
  logback.xml: {{- .Values.cortex.logbackXml | toYaml | indent 1 }}
  {{- end }}
{{- end -}}
