{{- if or (.Values.cortex.configFile) (.Values.cortex.logbackXml) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortex.fullname" . }}-config
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
data:
  {{- if .Values.cortex.configFile }}
  application.conf: {{- .Values.cortex.configFile | toYaml | indent 1 }}
  {{- end }}
  {{- if .Values.cortex.logbackXml }}
  logback.xml: {{- .Values.cortex.logbackXml | toYaml | indent 1 }}
  {{- end }}
{{- end -}}
