{{- if .Values.cortex.persistentVolumeClaim.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cortex.persistentVolumeClaimName" . }}
  {{- with .Values.cortex.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.cortex.persistentVolumeClaim.size }}
{{- if .Values.cortex.persistentVolumeClaim.storageClass }}
{{- if (eq "-" .Values.cortex.persistentVolumeClaim.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.cortex.persistentVolumeClaim.storageClass }}"
{{- end -}}
{{- end -}}
{{- end -}}
