{{- if or (not .Values.cortex.index.k8sSecretName) (not .Values.cortex.k8sSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cortex.fullname" . }}-secrets
  {{- with .Values.cortex.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.cortex.index.k8sSecretName }}
  CORTEX_ELASTICSEARCH_PASSWORD: {{ .Values.cortex.index.password | b64enc | quote }}
  {{- end }}
  {{- if not .Values.cortex.k8sSecretName }}
  SECRET: {{ .Values.cortex.httpSecret | b64enc | quote }}
  {{- end }}
{{- end }}
