{{- if not .Values.cortex.k8sSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cortex.fullname" . }}-secrets
  {{- with .Values.cortex.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET: {{ .Values.cortex.httpSecret | b64enc | quote }}
{{- end }}
