{{- if .Values.cortex.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cortex.serviceAccountName" . }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
  {{- with .Values.cortex.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.cortex.serviceAccount.automountServiceAccountToken }}
{{- end -}}
