apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.fullname" . }}
  {{- with .Values.cortex.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cortex.service.type }}
  ports:
    - port: {{ .Values.cortex.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cortex.matchLabels" . | nindent 4 }}
