################ GLOBAL CONFIGS
hostname:
  cassandra:
    value: "cassandra.cassandra.svc.cluster.local"
    user: cassandra
    password: cassandra
    clustername: thp
    keyspace: thehive

  elasticSearch:
    value: "elasticsearch.elasticsearch.svc.cluster.local"
    index: thehive
    
  minio:
    value: "minio.minio.svc.cluster.local"
    accessKey: minioadmin
    secretKey: minioadmin
    bucket: thehive

################## THEHIVE CONFIGS
theHiveApp:
  # baseUrl should be changed to reflect how the application is exposed
  baseUrl: "http://localhost:9000"
  # Change application secret
  secret: QCY?tAnfk?aZ?iwrNwnxIlR6CTf:G3gf:90Latabg@5241AB`R5W:1uDFN];Ik@n

  service:
    type: LoadBalancer
    port: 9000
    nodePort: 30021

  statefulset:
    replicas: 1
    containerPort: 9000
    name: http
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: "100m"
        memory: 100Mi
    image: strangebee/thehive:latest

TheHiveStorageClass:
  cloud: thehive-local
  name: thehive-storageclass
  reclaimPolicy: Retain

TheHivePersistentVolumeClaim:
  name: thehive-pvc
  spec:
    accessModes: ReadWriteOnce
    resources:
      requests:
        storage: 2Gi

TheHivePersistentVolume:
  name: thehive-pv
  spec:
    accessModes: ReadWriteOnce
    capacity:
      storage: 5Gi
    hostPath:
      dirPath: /hive

######################### CORTEX CONFIGS
cortex:
  service:
    port: 9001
    targetPort: 9001
  statefulset:
    replicas: 1
    terminationGracePeriodSeconds: 1800
    containers:
      image: thehiveproject/cortex:latest
      ports:
        containerPort: 9001
        name: http
      resources:
        limits:
          cpu: "500m"
          memory: 1Gi
        requests:
          cpu: "100m"
          memory: 512Mi
    volumes:
      configMap:
        name: cortex-configmap
        items:
          key: application.conf
          path: application.conf

CortexStorageClass:
  cloud: local
  name: cortex-storageclass
  reclaimPolicy: Retain
  accessModes: ReadWriteMany

CortexPersistentVolume:
  name: cortex-pv
  accessModes: ReadWriteMany
  capacity:
    storage: 5Gi

CortexPersistentVolumeClaim:
  name: cortex-pvc
  spec:
    resources:
      storage: 4G

CortexHPA:
  name: cortex-autoscale
  spec:
    minReplicas: 1
    maxReplicas: 1
    metrics:
      averageUtilization: 90
      averageValue: 900Mi
