################ GLOBAL CONFIGS
hostname:
  cassandra:
    value: "cassandra.cassandra.svc.cluster.local"
    user: cassandra
    password: password
    clustername: thp
    keyspace: thehive
  elasticSearch:
    value: "elasticsearch.elasticsearch.svc.cluster.local"
    index: thehive
  minio:
    value: "minio.minio.svc.cluster.local"
    accessKey: minioadmin
    secretKey: minioadmin
    bucket: thehive

################## THEHIVE CONFIGS
theHiveApp:
  # baseUrl should be changed to reflect how the application is exposed
  baseUrl: "http://localhost:9000"
  # Change application secret
  secret: changeme

  service:
    type: LoadBalancer
    port: 9000
    nodePort: 30021

  statefulset:
    replicas: 1
    containerPort: 9000
    name: http
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: "100m"
        memory: 100Mi
    image: strangebee/thehive:latest

TheHiveStorageClass:
  cloud: thehive-local
  name: thehive-storageclass
  reclaimPolicy: Retain

TheHivePersistentVolumeClaim:
  name: thehive-pvc
  spec:
    accessModes: ReadWriteOnce
    resources:
      requests:
        storage: 2Gi

TheHivePersistentVolume:
  name: thehive-pv
  spec:
    accessModes: ReadWriteOnce
    capacity:
      storage: 5Gi
    hostPath:
      dirPath: /hive

####################### MINIO CONFIGS
minio:
  service:
    type: LoadBalancer
    apiName: api
    apiPort: 9017
    apitargetPort: 9000
    consoleName: console
    consolePort: 9018
    consoletargetPort: 9001
    consoleNodePort: 30018
  statefulset:
    replicas: 1
    terminationGracePeriodSeconds: 1800
    containers:
      image: quay.io/minio/minio
      ports:
        apiContainerPort: 9000
        apiName: api
        consoleContainerPort: 9001
        consoleName: console
      resources:
        limits:
          cpu: "500m"
          memory: 512Mi
        requests:
          cpu: "100m"
          memory: 100Mi

######################### CORTEX CONFIGS
cortex:
  service:
    port: 9001
    targetPort: 9001
  statefulset:
    replicas: 1
    terminationGracePeriodSeconds: 1800
    containers:
      image: thehiveproject/cortex:3.1.1-1
      ports:
        containerPort: 9001
        name: http
      resources:
        limits:
          cpu: "500m"
          memory: 1Gi
        requests:
          cpu: "100m"
          memory: 512Mi
    volumes:
      configMap:
        name: cortex-configmap
        items:
          key: application.conf
          path: application.conf

Secrets:
  name: minio-secrets

  user: minioadmin
  keyUser: MINIO_ROOT_USER

  password: minioadmin
  keyPassword: MINIO_ROOT_PASSWORD

CortexStorageClass:
  cloud: local
  name: cortex-storageclass
  reclaimPolicy: Retain
  accessModes: ReadWriteMany

CortexPersistentVolume:
  name: cortex-pv
  accessModes: ReadWriteMany
  capacity:
    storage: 5Gi

CortexPersistentVolumeClaim:
  name: cortex-pvc
  spec:
    resources:
      storage: 4G

CortexHPA:
  name: cortex-autoscale
  spec:
    minReplicas: 1
    maxReplicas: 1
    metrics:
      averageUtilization: 90
      averageValue: 900Mi
