{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thehive.serviceAccountName" . }}
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{ end -}}

{{- if .Values.serviceAccount.podReader.attach -}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "thehive.serviceAccountName" . }}-pod-reader
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "thehive.serviceAccountName" . }}-read-pods
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "thehive.serviceAccountName" . }}
roleRef:
  kind: Role
  {{- if .Values.serviceAccount.podReader.serviceAccountName }}
  name: {{ .Values.serviceAccount.podReader.serviceAccountName }}
  {{- else}}
  name: {{ include "thehive.serviceAccountName" . }}-pod-reader
  {{- end }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}