# https://helm.sh/docs/topics/charts/#the-chartyaml-file
apiVersion: v2

name: thehive
version: 0.4.7
appVersion: "5.5.12-1"
kubeVersion: ">= 1.23.0-0"

dependencies:
  - name: cassandra
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 12.3.13
    condition: cassandra.enabled
  - name: elasticsearch
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 22.1.6
    condition: elasticsearch.enabled
  - name: minio
    repository: https://charts.min.io
    version: 5.4.0
    condition: minio.enabled

type: application
description: The official Helm Chart of TheHive for Kubernetes
icon: https://strangebeecorp.github.io/helm-charts/assets/thehive-icon.svg
keywords:
  - thehive
  - sirp
  - incident-response
  - case-management
  - strangebee

home: https://strangebee.com/thehive/
sources:
  - https://github.com/StrangeBeeCorp/helm-charts/tree/main/thehive-charts/thehive
maintainers:
  - name: StrangeBee
    url: https://strangebee.com/

# https://artifacthub.io/docs/topics/annotations/helm/
annotations:
  artifacthub.io/category: security
  artifacthub.io/images: |
    - name: thehive
      image: strangebee/thehive:5.5.12-1
      whitelisted: true
    - name: curl
      image: curlimages/curl:8.17.0
      whitelisted: true
  artifacthub.io/license: AGPL-3.0
  artifacthub.io/links: |
    - name: source
      url: https://github.com/StrangeBeeCorp/helm-charts/tree/main/thehive-charts/thehive
    - name: support
      url: https://strangebee.com/contact-strangebee/
