apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thehive.fullname" . }}-env
  {{- with .Values.thehive.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
data:
  TH_KUBERNETES: "1"
  TH_KUBERNETES_POD_LABEL_SELECTOR: {{ include "thehive.selectorLabelsForPekko" . }}
  TH_CLUSTER_MIN_NODES_COUNT: {{ .Values.thehive.clusterMinNodesCount | quote }}
  TH_CQL_USERNAME: {{ .Values.thehive.database.username | quote }}
  {{- if and (.Values.cassandra.enabled) (eq (len .Values.thehive.database.hostnames) 0) }}
  TH_CQL_HOSTNAMES: {{ printf "%s-cassandra" .Release.Name | trunc 63 | quote }}
  {{- else }}
  TH_CQL_HOSTNAMES: {{ join "," .Values.thehive.database.hostnames | quote }}
  {{- end }}
  {{- if .Values.thehive.database.wait }}
  TH_CQL_WAIT: "1"
  {{- else }}
  TH_CQL_WAIT: "0"
  {{- end }}
  TH_INDEX_BACKEND: "elasticsearch"
  TH_ELASTICSEARCH_USERNAME: {{ .Values.thehive.index.username | quote }}
  {{- if and (.Values.elasticsearch.enabled) (eq (len .Values.thehive.index.hostnames) 0) }}
  TH_ELASTICSEARCH_HOSTNAMES: {{ printf "%s-elasticsearch" .Release.Name | trunc 63 | quote }}
  {{- else }}
  TH_ELASTICSEARCH_HOSTNAMES: {{ join "," .Values.thehive.index.hostnames | quote }}
  {{- end }}
  {{- if .Values.thehive.storage.usePathAccessStyle }}
  TH_S3_USE_PATH_ACCESS_STYLE: "1"
  {{- else }}
  TH_S3_USE_PATH_ACCESS_STYLE: "0"
  {{- end }}
  TH_S3_ACCESS_KEY: {{ .Values.thehive.storage.accessKey | quote }}
  {{- if and (.Values.minio.enabled) (empty .Values.thehive.storage.endpoint) }}
  TH_S3_ENDPOINT: {{ printf "http://%s-minio:9000" .Release.Name | quote }}
  {{- else }}
  TH_S3_ENDPOINT: {{ .Values.thehive.storage.endpoint | quote }}
  {{- end }}
  TH_S3_BUCKET: {{ .Values.thehive.storage.bucket | quote }}
  TH_S3_REGION: {{ .Values.thehive.storage.region | quote }}
  {{- if .Values.thehive.cortex.enabled }}
  TH_NO_CONFIG_CORTEX: "0"
  TH_CORTEX_PROTO: {{ .Values.thehive.cortex.protocol | quote }}
  TH_CORTEX_HOSTNAMES: {{ join "," .Values.thehive.cortex.hostnames | quote }}
  TH_CORTEX_PORT: {{ .Values.thehive.cortex.port | quote }}
  {{- else }}
  TH_NO_CONFIG_CORTEX: "1"
  {{- end }}
