{{- if or (.Values.thehive.configFile) (.Values.thehive.logbackXml) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thehive.fullname" . }}-config
  {{- with .Values.thehive.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
data:
  {{- if .Values.thehive.configFile }}
  application.conf: {{- .Values.thehive.configFile | toYaml | indent 1 }}
  {{- end }}
  {{- if .Values.thehive.logbackXml }}
  logback.xml: {{- .Values.thehive.logbackXml | toYaml | indent 1 }}
  {{- end }}
{{- end }}
