{{- if or (.Values.thehive.applicationConf) (.Values.thehive.logbackXml) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thehive.fullname" . }}-config
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
data:
  {{- if .Values.thehive.applicationConf }}
  application.conf: {{- .Values.thehive.applicationConf | toYaml | indent 1 }}
  {{- end }}
  {{- if .Values.thehive.logbackXml }}
  logback.xml: {{- .Values.thehive.logbackXml | toYaml | indent 1 }}
  {{- end }}
{{- end }}
