{{- if .Values.thehive.ingress.enabled -}}
{{- $fullName := include "thehive.fullname" . -}}
{{- $servicePort := .Values.thehive.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
  {{- with .Values.thehive.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.thehive.ingress.className }}
  ingressClassName: {{ .Values.thehive.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.thehive.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
          {{- end }}
    {{- end }}
  {{- with .Values.thehive.ingress.tls }}
  tls:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
