apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "thehive.fullname" . }}
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.thehive.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "thehive.fullname" . }}
