{{- if or (not .Values.thehive.database.k8sSecretName) (not .Values.thehive.index.k8sSecretName) (not .Values.thehive.storage.k8sSecretName) (not .Values.thehive.k8sSecretName) (and (.Values.thehive.cortex.enabled) (not .Values.thehive.cortex.k8sSecretName)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thehive.fullname" . }}-secrets
  {{- with .Values.thehive.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.thehive.database.k8sSecretName }}
  TH_CQL_PASSWORD: {{ .Values.thehive.database.password | b64enc | quote }}
  {{- end }}
  {{- if not .Values.thehive.index.k8sSecretName }}
  TH_ELASTICSEARCH_PASSWORD: {{ .Values.thehive.index.password | b64enc | quote }}
  {{- end }}
  {{- if not .Values.thehive.storage.k8sSecretName }}
  TH_S3_SECRET_KEY: {{ .Values.thehive.storage.secretKey | b64enc | quote }}
  {{- end }}
  {{- if not .Values.thehive.k8sSecretName }}
  TH_SECRET: {{ .Values.thehive.httpSecret | b64enc | quote }}
  {{- end }}
  {{- if and (.Values.thehive.cortex.enabled) (not .Values.thehive.cortex.k8sSecretName) }}
  TH_CORTEX_KEYS: {{ join "," .Values.thehive.cortex.api_keys | b64enc | quote }}
  {{- end }}
{{- end }}
