{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thehive.serviceAccountName" . }}
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "thehive.serviceAccountName" . }}-pod-reader-binding
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "thehive.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "thehive.serviceAccountName" . }}-pod-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
