{{- if .Values.thehive.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thehive.serviceAccountName" . }}
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
  {{- with .Values.thehive.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.thehive.serviceAccount.automount }}
{{- end }}
