apiVersion: v1
kind: Service
metadata:
  name: {{ include "thehive.fullname" . }}
  {{- with .Values.thehive.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
spec:
  type: {{ .Values.thehive.service.type }}
  ports:
    - port: {{ .Values.thehive.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.thehive.monitoring.enabled }}
    - port: {{ .Values.thehive.monitoring.port }}
      targetPort: kamon
      protocol: TCP
      name: kamon
    {{- end }}
  selector:
    {{- include "thehive.matchLabels" . | nindent 4 }}
