{{- if .Values.minio.enabled }}
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  # This name uniquely identifies the Deployment
  name: {{ include "thehive.fullname" . }}-minio
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
  labels:
    {{ include "thehive.minio.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ include "thehive.minio.selectorLabels" . | nindent 6 }}
  serviceName: thehive-minio-svc
  volumeClaimTemplates:
      - metadata:
          name: thehive-minio-pv-claim
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: {{ .Values.minio.storage.volumeClaimValue  }}
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        {{ include "thehive.minio.labels" . | nindent 8 }}
    spec:
      # Refer to the PVC created earlier
      containers:
        - name: thehive-minio
          # Pulls the default Minio image from Docker Hub
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          args:
            - server
            - /storage
          env:
            # Minio access key and secret key. This must match the S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY declared in /dev/.env.
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.auth.rootUser  }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.auth.rootPassword }}
          ports:
            - containerPort: 9000
          # Mount the volume into the pod
          volumeMounts:
            - name: thehive-minio-pv-claim # must match the volume name, above
              mountPath: "/storage"
      {{- with .Values.minio.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.minio.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.minio.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
