apiVersion: v1
kind: Service
metadata:
  name: opensearch-external
spec:
  ports:
    - port: 9200
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: opensearch-external-1
  labels:
    kubernetes.io/service-name: opensearch-external
addressType: IPv4
endpoints:
  - addresses:
      - "${HOST_IP}"
ports:
  - port: 9200
