{{- if .Values.cassandra.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thehive-cassandra
    {{- include "thehive.labels" . | nindent 4 }}
  name: {{ include "thehive.fullname" . }}-cassandra
spec:
  ports:
    - port: 9042
  selector:
    app: thehive-cassandra
{{- end}}