services:
  elasticsearch:
    image: docker.io/elasticsearch:8.17.2
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      cluster.name: "cortex"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 30
