{{- if .Values.cassandra.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "thehive.cassandra.labels" . | nindent 4 }}
  name: {{ include "thehive.fullname" . }}-cassandra
spec:
  ports:
    - port: 9042
  selector:
    {{- include "thehive.cassandra.selectorLabels" . | nindent 4 }}
{{- end}}
