{{- if .Values.cassandra.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "thehive.fullname" . }}-cassandra
  labels:
    {{- include "thehive.cassandra.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "thehive.fullname" . }}-cassandra
  {{- if .Values.cassandra.persistence.enabled }}
  volumeClaimTemplates:
      - metadata:
          name: thehive-cassandra-pv-claim
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: {{ .Values.cassandra.persistence.storageClass }}
          volumeMode: {{ .Values.cassandra.persistence.volumeMode }}
          resources:
            requests:
              storage: {{ .Values.cassandra.persistence.size }}
  {{- end }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "thehive.cassandra.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thehive.cassandra.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
        - name: cassandra
          image: "{{ .Values.cassandra.image.registry }}/{{ .Values.cassandra.image.repository }}:{{ .Values.cassandra.image.tag }}"
          imagePullPolicy: {{ .Values.cassandra.image.pullPolicy }}
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          resources:
            {{- toYaml .Values.cassandra.resources | nindent 12 }}
          #securityContext:
          #  capabilities:
          #    add:
          #      - IPC_LOCK
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - nodetool drain
          env:
            - name: MAX_HEAP_SIZE
              value: "{{ .Values.cassandra.maxHeapSize }}"
            - name: HEAP_NEWSIZE
              value: "{{ .Values.cassandra.heapNewSize }}"
            - name: JVM_OPTS
              value: "-Xms{{ .Values.cassandra.xms }} -Xmx{{ .Values.cassandra.xmx }} -Xmn{{ .Values.cassandra.xmn }}"
            - name: CASSANDRA_CLUSTER_NAME
              value: "{{ .Values.cassandra.clusterName }}"
            - name: CASSANDRA_DC
              value: "{{ .Values.cassandra.dcName }}"
            - name: CASSANDRA_RACK
              value: "{{ .Values.cassandra.rackName }}"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- if eq .Values.cassandra.persistence.volumeMode "Block" }}
          volumeDevices:
            - name: thehive-cassandra-pv-claim
              devicePath: /var/lib/cassandra
          {{- else }}
          volumeMounts:
            - name: thehive-cassandra-pv-claim
              mountPath: /var/lib/cassandra
          {{- end }}
      {{- if not .Values.cassandra.persistence.enabled }}
      volumes:
        - name: cassandra-data
          emptyDir: {}
      {{- end }}
{{- end}}
