version: 0.1.7
apiVersion: v2
appVersion: "5.4.5-1"
name: thehive
description: The official Helm chart of TheHive for Kubernetes.
type: application

maintainers:
  - name: StrangeBee
    url: https://strangebee.com/

keywords:
  - thehive
  - sirp
  - incident-response
  - case-management
  - strangebee

icon: https://strangebeecorp.github.io/helm-charts/assets/thehive-icon.svg
home: https://github.com/StrangeBeeCorp/helm-charts
sources:
  - https://github.com/StrangeBeeCorp/helm-charts/tree/main/charts/thehive

dependencies:
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled

annotations:
  artifacthub.io/license: AGPL-3.0
  artifacthub.io/links: |
    - name: Community
      url: https://chat.thehive-project.org
  artifacthub.io/images: |
    - name: busybox
      image: busybox:1.28
      whitelisted: true
    - name: cassandra
      image: cassandra:4.1
      whitelisted: true
    - name: thehive
      image: strangebee/thehive:5.2
      whitelisted: true

## For reference:
## https://helm.sh/docs/topics/charts/#the-chartyaml-file
## https://artifacthub.io/docs/topics/annotations/helm/
