# Default values for thehive.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: docker.io
  repository: strangebee/thehive
  # Defaults to the chart appVersion, can be overridden here
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

cassandra:
  # -- Enable Cassandra database
  enabled: true
  image:
    registry: docker.io
    repository: cassandra
    tag: "4.1.7"
    pullPolicy: IfNotPresent
  # -- Cassandra cluster name
  clusterName: "TheHive"
  # -- Cassandra datacenter name
  dcName: "DC1-TheHive"
  # -- Cassandra rack name
  rackName: "Rack1-TheHive"
  resources:
    limits:
      cpu: "1000m"
      memory: "2Gi"
    requests:
      cpu: "1000m"
      memory: "2Gi"
  # -- Cassandra max heap size
  maxHeapSize: "512M"
  # -- Cassandra heap new size
  heapNewSize: "128M"
  # -- Cassandra Xms
  xms: "128M"
  # -- Cassandra Xmx
  xmx: "512M"
  # -- Cassandra Xmn
  xmn: "128M"
  persistence:
    # -- Enable Cassandra persistence
    enabled: true
    # -- Cassandra storageClass
    storageClass: "standard"
    # -- Cassandra persistent volume size
    size: "2Gi"
    # -- Cassandra volume mode (Filesystem or Block)
    volumeMode: Filesystem


# https://github.com/bitnami/charts/blob/elasticsearch/21.3.26/bitnami/elasticsearch/values.yaml
elasticsearch:
  # Use ElasticSearch dependency Helm Chart
  enabled: true

  image:
    registry: docker.io
    repository: bitnami/elasticsearch
    tag: "8.16.1-debian-12-r1"

  master:
    # Use master nodes as multipurpose nodes (master, data, coordinating and ingest) to simplify the deployment
    masterOnly: false
    # Number of master-elegible replicas to deploy
    replicaCount: 2
    # Defined in https://github.com/bitnami/charts/blob/elasticsearch/21.3.26/bitnami/common/templates/_resources.tpl
    resourcesPreset: "small"
    # Master nodes heap size
    heapSize: 96m
    # Configure JVM options as env variable
    extraEnvVars:
      - name: JVM_OPTS
        value: "-Xms96m -Xmx96m -Xmn96m"
    # WARNING - should be set to "hard" or configured manually with "elasticsearch.master.affinity" in production
    podAffinityPreset: "soft"

  data:
    # Disable data-dedicated nodes
    replicaCount: 0

  coordinating:
    # Disable coordination-dedicated nodes
    replicaCount: 0

  ingest:
    # Disable ingestion-dedicated nodes
    replicaCount: 0

  security:
    # WARNING - security options should be enabled in production
    enabled: false


minio:
  # -- Enable Minio
  enabled: true
  # -- Minio endpoint
  endpoint: http://thehive-minio:9000

  image:
    registry: docker.io
    repository: minio/minio
    tag: RELEASE.2024-11-07T00-52-20Z
    pullPolicy: IfNotPresent

  # -- MinIO client image
  minioClient:
    image:
      registry: docker.io
      repository: minio/mc
      tag: RELEASE.2024-11-17T19-35-25Z
      pullPolicy: IfNotPresent

  # -- Minio authentification configuration
  auth:
    rootUser: minio
    rootPassword: minio123
  # -- Minio storage configuration
  storage:
    volumeClaimValue: "2Gi"
  nodeSelector: {}
  tolerations: []
  affinity: {}

busybox:
  image:
    registry: docker.io
    repository: busybox
    tag: "1.36-glibc"
    pullPolicy: IfNotPresent

thehive:
  # -- Init containers will execute nslookup to resolve the hostnames of cassandra and elasticsearch
  initContainers:
    # -- Enable init containers
    enabled: true
  # -- PodDisruptionBudget configuration
  maxUnavailable: 1
  # -- TheHive Secret (must be at least 32 characters long)
  secret: "YouShouldChangeThisSecretWithOneOfAtLeast32Chars"
  # -- TheHive Nodes count
  clusterMinNodesCount: 1
  # -- Cortex configuration
  cortex:
    enabled: false
    # -- Cortex hostnames
    hostnames:
      - "thehive-cortex"
    keys: ""
  # -- Cassandra configuration
  cql:
    # -- Cassandra hostnames
    hostnames:
      - "thehive-cassandra"
    # -- Wait for Cassandra
    wait: true
  # Index backend configuration
  indexBackend:
    type: elasticsearch
    # ElasticSearch cluster hostnames
    hostnames:
      - "thehive-elasticsearch"
    # ElasticSearch API port
    port: "9200"
  # -- Object Storage configuration
  # @default -- {}
  s3:
    # -- S3 Endpoint
    endpoint: "http://thehive-minio:9000"
    # -- S3 Access key
    accessKey: "minio"
    # -- S3 Secret key
    secretKey: "minio123"
    # -- S3 Access Style
    usePathAccessStyle: true
  # -- Custom application.conf file for TheHive
  extraConfig: ""
  #extraConfig: |-
  #  # TheHive configuration file
  # -- Extra entrypoint arguments. See: https://docs.strangebee.com/thehive/setup/installation/docker/#all-options
  extraCommand: []
  # -- Extra environment variables
  extraEnv: []
  #- name: "EXAMPLE"
  #  value: "example"
  # -- Liveness probes
  livenessProbe:
    enabled: true
  # -- Readiness probes
  readinessProbe:
    enabled: true

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # -- If not set and create is true, a name is generated using the fullname template
  name: ""
  # -- Attach pod reader role to service account
  podReader:
    # -- Specifies whether a pod reader role should be attached. Required to running thehive in cluster mode
    attach: true
    # -- The name of the service account to map pod reader role.
    serviceAccountName: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
