{{- if .Values.cassandra.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-cassandra
  name: {{ .Release.Name }}-cassandra
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{.Values.cassandra.service.port}}
  selector:
    app: {{ .Release.Name }}-cassandra
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-cassandra
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-cassandra
spec:
  serviceName: {{ .Release.Name }}-cassandra
  replicas: {{ .Values.cassandra.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cassandra
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cassandra
    spec:
      terminationGracePeriodSeconds: {{ .Values.cassandra.statefulset.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Release.Name }}-cassandra
          image: {{ .Values.cassandra.statefulset.image }}
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          resources:
            limits:
              cpu: {{ .Values.cassandra.statefulset.resources.limits.cpu }}
              memory: {{ .Values.cassandra.statefulset.resources.limits.memory }}
            requests:
              cpu: {{ .Values.cassandra.statefulset.resources.requests.cpu }}
              memory: {{ .Values.cassandra.statefulset.resources.requests.memory }}
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - nodetool drain
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_CLUSTER_NAME
              value: "TheHive"
            - name: CASSANDRA_DC
              value: "DC1-TheHive"
            - name: CASSANDRA_RACK
              value: "Rack1-TheHive"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          # These volume mounts are persistent. They are like inline claims,
          # but not exactly because the names need to match exactly one of
          # the stateful pod volumes.
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
      volumes:
        - name: cassandra-data
          emptyDir: {}
{{- end }}