{{- if .Values.elasticSearch.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-elasticsearch
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-elasticsearch
spec:
  serviceName: {{ .Release.Name }}-elasticsearch
  replicas: {{ .Values.elasticSearch.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-elasticsearch
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-elasticsearch
    spec:
      terminationGracePeriodSeconds: {{ .Values.elasticSearch.statefulset.terminationGracePeriodSeconds }}
      initContainers:
        - name: {{ .Values.elasticSearch.statefulset.initContainers.name }}
          image: {{ .Values.elasticSearch.statefulset.initContainers.image }}
          command:
            - bash
            - "-c"
            - "mkdir -p /usr/share/elasticsearch/data && chmod -R 777 /usr/share/elasticsearch/data"
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: {{ .Release.Name }}-elasticsearch
          image: {{ .Values.elasticSearch.statefulset.containers.image }}
          ports:
            - containerPort: {{ .Values.elasticSearch.statefulset.containers.ports.containerPort }}
              name: {{ .Values.elasticSearch.statefulset.containers.ports.name }}
          resources:
            limits:
              cpu: {{ .Values.elasticSearch.statefulset.containers.resources.limits.cpu }}
              memory: {{ .Values.elasticSearch.statefulset.containers.resources.limits.memory }}
            requests:
              cpu: {{ .Values.elasticSearch.statefulset.containers.resources.requests.cpu }}
              memory: {{ .Values.elasticSearch.statefulset.containers.resources.requests.memory }}
          env:
            - name: "node.name"
              value: es
            - name: "cluster.name"
              value: es-docker-cluster
            - name: "discovery.type"
              value: single-node
            - name: "bootstrap.memory_lock"
              value: "true"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: "xpack.security.enabled"
              value: "false"
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-data
          emptyDir: {}
{{- end }}
