apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-minio
  name: {{ .Release.Name }}-minio
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.minio.service.port }}
  selector:
    app: {{ .Release.Name }}-minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-minio
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-minio
spec:
  serviceName: {{ .Release.Name }}-minio
  replicas: {{ .Values.minio.statefulset.replicas }}
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      terminationGracePeriodSeconds: {{ .Values.minio.statefulset.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Release.Name }}-minio
          image: {{ .Values.minio.statefulset.containers.image }}
          command: ["minio", "server", "/data", "--console-address", ":9001"]
          env:
            - name: MINIO_ROOT_USER
              value: minioadmin
            - name: MINIO_ROOT_PASSWORD
              value: minioadmin
          ports:
            - containerPort: {{ .Values.minio.statefulset.containers.ports.containerPort }}
              name: {{ .Values.elasticSearch.statefulset.containers.ports.name }}
          resources:
            limits:
              cpu: {{ .Values.minio.statefulset.containers.resources.limits.cpu }}
              memory: {{ .Values.minio.statefulset.containers.resources.limits.memory }}
            requests:
              cpu: {{ .Values.minio.statefulset.containers.resources.requests.cpu }}
              memory: {{ .Values.minio.statefulset.containers.resources.requests.memory }}
          volumeMounts:
            - name: s3-data
              mountPath: /data
      volumes:
        - name: s3-data
          emptyDir: {}