apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.minio.service.port }}
  selector:
    app: minio
