apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - name: {{ .Values.minio.service.consoleName }}
      port: {{ .Values.minio.service.consolePort }}
      targetPort: {{ .Values.minio.service.consoletargetPort }}
      nodePort: {{ .Values.minio.service.consoleNodePort }}
  selector:
    app: {{ .Release.Name }}

