####################### MINIO CONFIGS
minio:
  service:
    type: LoadBalancer
    # apiName: api
    # apiPort: 9017
    # apitargetPort: 9000
    consoleName: console
    consolePort: 9018
    consoletargetPort: 9001
    consoleNodePort: 30018
  statefulset:
    replicas: 1
    terminationGracePeriodSeconds: 1800
    containers:
      image: quay.io/minio/minio
      ports:
        # apiContainerPort: 9000
        # apiName: api
        consoleContainerPort: 9001
        consoleName: console
      resources:
        limits:
          cpu: "500m"
          memory: 512Mi
        requests:
          cpu: "100m"
          memory: 100Mi

Secrets:
  name: minio-secrets
  
  user: minioadmin
  keyUser: MINIO_ROOT_USER
  
  password: minioadmin
  keyPassword: MINIO_ROOT_PASSWORD


MinioStorageClass:
  cloud: minio-local
  name: minio-storageclass
  reclaimPolicy: Retain

MinioPersistentVolumeClaim:
  name: minio-pvc
  spec:
    accessModes: ReadWriteOnce
    resources:
      requests:
        storage: 2Gi

MinioPersistentVolume:
  name: minio-pv
  spec:
    accessModes: ReadWriteOnce
    capacity:
      storage: 5Gi
    hostPath:
      dirPath: /minio

