# Based on https://github.com/helm/chart-releaser-action
name: Release Cortex Helm Chart

on:
  push:
    tags:
      - cortex-*

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # At the time of writing, the "helm/chart-releaser-action" does not support multiple Helm Charts
      # https://github.com/helm/chart-releaser-action/issues/198
      #
      # We use separate folders for TheHive and Cortex charts as a workaround
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: cortex-charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
