# Based on https://github.com/helm/chart-releaser-action
name: Release TheHive Helm Chart

on:
  push:
    tags:
      - thehive-*

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add Helm Repositories related to the Helm Charts specified as dependencies
        run: |
          helm repo add minio https://charts.min.io/

      # At the time of writing, the "helm/chart-releaser-action" does not support multiple Helm Charts
      # https://github.com/helm/chart-releaser-action/issues/198
      #
      # For now we only have TheHive Helm Chart defined, but adding other Charts will create issues
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
